version: "3.7"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: crm-service
    command:
      - yarn
      - start:dev
    volumes:
      - "../app/src:/var/app/src"
    env_file:
      - ../env/docker.env
      - ../env/docker.secrets.env
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: crm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: localpassword
